name: ml
channels:
  - conda-forge
  - r
dependencies:
  - r-caret=6.0
  - r-e1071
  - r-docopt=0.6.1
  - r-kernlab=0.9
  - r-liblinear=2.10
  - r-proc=1.15.0
  - r-randomforest=4.6
  - r-rpart=4.1
  - r-tictoc=1.0
  - r-tidyverse=1.2.1
  - r-xgboost=0.90
  - r-yaml=2.2.0
